### PR TITLE
Added some tests

### PR DESCRIPTION
**Pull request by briochemc**
Hi,

I added some tests to improve coverage on the existing file, and added a few random functions tested at some random values (which include the two functions that are in `test_power`) — See new file `test/test_function_list.jl`.

In this new file, I also left a comment at the start describing how to make the list of functions to be tested, if you want to add some (although this is only using sagemath). This workflow is not perfect, as some function names are different (e.g., `conj` becomes `conjugate` in sage, and the derivative of `abs` is defined via `conjugate`, so I could not use `abs` directly). Maybe with time Julia will have its own symbolic differentiation package and we can plug it in there instead of relying on other languages like Mathematica, Maple, or sagemath.

### CODE REVIEW

**Comment by goedman** [comment]
Hi Benoit,

This is great!

For another package I relied on Symata.jl. As an example I added a file test_symata.jl which should work if Symata.jl is installed.

If I understand it correctly we could add Symata just for testing in the [test] section in Project.toml, thus it is not required for 'normal' usage of HyperDualNumbers.jl.

Also, I'm trying to reformat your last list of improvements into a kind of TODO list.

As far as documentation is concerned I would have a preference to use Literate.jl to generate the docs and in fact notebooks from a marked-up .jl file.

I do agree I moved quickly with merging your updates into master but my experience has been by putting it out there lost of good feedback is obtained. 

Best,
Rob

**Comment by goedman** [comment]
The output of test_symata.jl in the REPL:

```
julia> include("/Users/rob/.julia/dev/HyperDualNumbers/test/test_symata.jl")
[ Info: Precompiling Symata [a906b1d5-d016-55c4-aab3-8a20cba0db2a]
WARNING: could not import Base.Test into Symata
WARNING: could not import Base.search into Symata
WARNING: could not import Base.next into Symata

f1(x) = (Cos(x)^2 - Log(Sin(x))*Sin(x)^2)*Sin(x)^(-1 + Cos(x))
f2(x) = ((-Cos(x)^2 + Log(Sin(x))*Sin(x)^2)^2 - Cos(x)*(Cos(x)^2 + (3 + Log(Sin(x)))*Sin(x)^2))*Sin(x)^(-2 + Cos(x))

"(Cos(x)^2 - Log(Sin(x))*Sin(x)^2)*Sin(x)^(-1 + Cos(x))"

"((-Cos(x)^2 + Log(Sin(x))*Sin(x)^2)^2 - Cos(x)*(Cos(x)^2 + (3 + Log(Sin(x)))*Sin(x)^2))*Sin(x)^(-2 + Cos(x))"

1.8437433002891825 - 2.475293666210764im
-6.812169637209673 - 5.625583859353504im

julia> versioninfo()
Julia Version 1.1.0-DEV.700
Commit 464397e714* (2018-11-21 05:14 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.2.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG3_PRECOMPILE = true
  JULIA_CMDSTAN_HOME = /Users/rob/Projects/StanSupport/cmdstan
  JULIA_EDITOR = see
  JULIA_SVG_BROWSER = Google Chrome.app
  JULIA_SPECIALFUNCTIONS_BUILD_SOURCE = true
```

**Comment by briochemc** [comment]
Hi Rob, 

I am discovering both Symata.jl and Literate.jl...

1. About Syamta.jl, I like the idea of generating lists of expressions of first and second derivatives all in Julia, but I am unsure I would be able to pull it off: It currently seems to me that it would be a lot more work than the sagemath/mathematica workflow... Anyway, if we want to use Symata.jl, I think we should:
    1. First, ask the maintainers of DiffRules.jl and DualNumbers.jl (and any other autodiff related package that comes to mind actually) how they generate their own lists of derivatives.
    2. Suggest to add the Symata code, which generates *central* lists of derivatives, in DiffRules.jl. This would allow more collaborators to get it done the right way and then the packages like DualNumbers.jl, HyperDualNumbers.jl, ForwardDiff.jl, etc. could simply pull the generated list (or the generating code) to define their own overloads and tests.

2. Literate.jl is a tool to generate both what Documenter.jl needs and what Jupyter notebooks need, right? I.e., one writes only one source file for documentation using the Literate.jl syntax, and then the `md` file for Documenter.jl and the `ipynb` file for Jupyter Notebooks can be generated automatically. I guess all of this is automated by adding some lines to the CI `yaml` scripts. So as far as I understand it, I agree using Literate.jl is a good idea!

**Comment by goedman** [comment]
Hi Benoit,

Recently I have been experimenting with Literate.jl (in a new package I’m working on in StanJulia, StatisticalRethinking.jl to accompany McElreath’s book). And I like Literate a lot. You’re correct, from a, possibly annotated, .jl file it generates .md and .ipynb files.

On Symata it might help if we have a working version or skeleton, for both the list and testing purposes. Shall I take a stab at that?

I’m also looking into updating Travis testing and adding doc building at the same time.

Rob

**Comment by briochemc** [comment]
> Recently I have been experimenting with Literate.jl (in a new package I’m working on in StanJulia, StatisticalRethinking.jl to accompany McElreath’s book). And I like Literate a lot. You’re correct, from a, possibly annotated, .jl file it generates .md and .ipynb files.

Yes I just realized you were behind JuliaStan.jl too :) I have not used it myself but my PI has. I might look into it in the near future!

> On Symata it might help if we have a working version or skeleton, for both the list and testing purposes. Shall I take a stab at that?

Yes that's a good idea, if you can use Symata.jl to generate a list of the type
```julia
list = [
( :symbol_for_function, :( expression_for_1st_derivative ), :( expression_for_2st_derivative ) )
( :symbol_for_function, :( expression_for_1st_derivative ), :( expression_for_2st_derivative ) )
( :symbol_for_function, :( expression_for_1st_derivative ), :( expression_for_2st_derivative ) )
]
```
then we can use it to generate the overloads and tests! (And suggest it on DiffRules.jl)

**Pull request merged**
