### PR TITLE
Added Erf function

### PR DESCRIPTION
**Pull request by rcalxrc08**
I added Erf function in order to compute derivatives also for this function.

### CODE REVIEW

**Comment by goedman** [comment]
Hi @rcalxrc08 
Should we also add a test to runtests.jl?
Regards,
Rob

**Comment by rcalxrc08** [comment]
Added, do you have any idea why it is failing on te Julia Nightly? i have Julia 0.5.2 on local so i cannot test it.

**Comment by goedman** [comment]
Yes, we need to add SpecialFunctions.jl to REQUIRE. You can do it (or I can do that later today or tomorrow). I need to update the README and .travis.yml anyway and also enable testing on Windows.
But let's go step by step and merge your changes when it passes Travis.

**Comment by goedman** [comment]
Later today (will be driving next 5 hours or so through CO) I'll do a few more cleanups. Thanks for your help!

**Comment by rcalxrc08** [comment]
I am sorry but i have never used the latest version of julia and i haven't it in local so i could not test.
I made some try and finally works.
It has been an honour! thank you for this awesome library!

**Pull request merged**
