### PR TITLE
apply the DualNumbers structure to HyperDualNumbers and other things

### PR DESCRIPTION
**Pull request by briochemc**
Hi,

I decided to try to rewrite HyperDualNumbers.jl by starting from DualNumbers.jl and expanding on it.

I had to make some decisions:
- I redefined `abs` in such a way that the 2nd derivative of `abs(-x^2)` is correct at `0`. (Additionally, I think that the previous `abs(x) = sqrt(x^2)` was quite slower — compare e.g., with `Base.abs`.)
- I did not include some functions (sometimes on purpose, sometimes because I did not know what to do with them). But I thought I should raise the issue that some functions should *not* be available for differentiation in &#x2102; because they are differentiable *nowhere*. Namely functions that inject into &#x211d;, like `abs` or `angle`, but also some quite common functions like `conj`. (The functions that are &#x2102;-differentiable should be in the code though.)
- I chose to write my own list of first and second derivatives (using sagemath) to use for overloading most of the functions (like `cos`, `sin`, etc.). This was to match DualNumbers.jl's approach (which uses a list in [Calculus.jl](https://github.com/JuliaMath/Calculus.jl/blob/master/src/differentiate.jl). (I saw that [ForwardDiff.jl](https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/src/dual.jl) uses [DiffRules.jl](https://github.com/JuliaDiff/DiffRules.jl/blob/master/src/rules.jl) instead — so maybe this is were this list should go to be used by all other packages?)
- I renamed a few things to match the DualNumbers.jl nomenclature (e.g., `realpart`) and tried to keep aliases to older definitions (e.g., `eps1eps2` is replaced by a clearer `ε₁ε₂part` to match the `realpart` construct, but `eps1eps2` still available for backward compatibility)
- I changed a few tests from `a == b` to `isequal(a, b)` on purpose because `==` only compared the real part (`h/h == 1` would give true even if the non-real parts are wrong for example).

Anyway, I hope this is useful! Let me know what you think!

### CODE REVIEW

**Comment by goedman** [comment]
Hi Benoit, thank you very much! This is a huge leap forward.

I'm playing around with it right now (to un-learn old habits?) and studying how you approached/updated it.

My plan it to release this as version 4.0.0 and see if we get other feedback. I'll update/restructure the README (and add proper credits).

Thanks again for your help!

**Comment by briochemc** [comment]
Hi Rob,

I didn't expect you to merge this right away as it is quite different! 😄 

Please don't hesitate to comment on the code and on the things I brought up above. Another thing that would be nice would be to benchmark the different versions? (This might show us that something was better before, and hence worth reverting back?)

A few things that I think can improve the package further:
- [ ] Make sure no functionality from the former versions has been lost. (I.e., go through the older version code and check that it is also present in some form in the new version)
- [ ] Make sure that all the code is covered in the tests (the coverage seems a bit buggy but it still is helpful to spot some untested lines, e.g., `isfinite` right now is not tested I think.)
- [ ] Add all the tests in DualNumbers.jl (and convert them to hyper duals)
- [ ] Add the functions that I omitted from the list of predefined derivatives. (I did not find how to do some of them in sagemath). As I mentioned earlier, ForwardDiff.jl and DualNumbers.jl use different lists (from Calculus.jl and DiffRules.jl, respectively), so maybe a clean solution is to:
    1. Merge all three lists into a single list of functions
    2. Split into 2 lists: one for first derivatives and one for first and second derivatives
    3. Suggest both lists via a pull request to DiffRules.jl
    4. Remove the list in HyperDualNumbers.jl and use the one in DiffRules.jl instead
- [ ] Add documentation  in the `src/` code for the functions and constants that are exported, so that one can, e.g., call `help?> eps1eps2` or `help?> ε₁` to figure out what these do/are. This would then facilitate the next step: to create the documentation in github-pages via Documenter.jl.

**Comment by goedman** [comment]
Hi Benoit, wow, I'm impressed!

After 4.0.0 has been out there for a while, I think I'll deprecate hyper, eps1, eps2 and eps1eps2.

I did try:
```
Julia> Dict(hd=>"$hd", hd2=>"$(hd^2)")
Dict{Hyper{Float64},String} with 2 entries:
  2.0+1.0ε₁+1.0ε₂+3.0ε₁ε₂  => "2.0 + 1.0ε₁ + 1.0ε₂ + 3.0ε₁ε₂"
  4.0+4.0ε₁+4.0ε₂+14.0ε₁ε₂ => "4.0 + 4.0ε₁ + 4.0ε₂ + 14.0ε₁ε₂"
```

The derivative list is so much easier than sprinkling derivatives in hyperdual.jl and gave me some ideas for another project I'm working on!

In the README I'll add your list of decisions and some of your remarks/questions in comments in hyperdual.jl.

**Comment by goedman** [comment]
Hi Benoit,

I came across an issue with the definitions of ^() and added:

```
function Base.:^(x::Irrational{:ℯ}, h::Hyper)
    a, b, c, d = value(h), ε₁part(h), ε₂part(h), ε₁ε₂part(h)
    return Hyper(x^a,
        b*x^a*log(x),
        c*x^a*log(x),
        b*c*x^a*log(x)^2 + d*x^a*log(x))
end
function Base.:^(x::Number, h::Hyper)
    a, b, c, d = value(h), ε₁part(h), ε₂part(h), ε₁ε₂part(h)
    return Hyper(x^a,
        b*x^a*log(x),
        c*x^a*log(x),                                  # Had a typo: c*x^a*log(x)*z, ?
        b*c*x^a*log(x)^2 + d*x^a*log(x))
end
```

**Comment by briochemc** [comment]
Hi Rob,

About the typo: Yes — there does not seem to be a `z` defined anyway 😄 
Note it's not that surprising that there are typos: For the record, the way I got the algebra for the power law was to:
1. Use sagemath and Taylor expand
    ```sagemath
    (x + y * e1 + z * e2 + w * e1 * e2)^(a + b * e1 + c * e2 + d * e1 * e2)
    ```
    up to terms of order 2.
2. Then remove all squares, i.e., `e1^2` and `e2^2`
3. Finally copy the remaining terms in the Julia overload function. 
And all this copying and editing is prone to human errors!

So I think we need a proper set of tests for `^`! One idea is to use sagemath again, but this time to create symbolic expressions for the 1st and 2nd derivatives of `f(x)^g(x)` for a couple of functions `f(x)` and `g(x)` and test those at some random values for `x`.

**Comment by goedman** [comment]
Hi Benoit,

You mean something like in these to files:



Not sure if you have the Mathematica viewer, below a pdf version:





Running test_power.jl in Julia:

```
julia> f1(x) = x - x^3 + 4x^2
f1 (generic function with 1 method)

julia> 

julia> f2(x)  = x^2 - x
f2 (generic function with 1 method)

julia> 

julia> t0 = Hyper(2.0, 1.0, 1.0, 0.0)
2.0 + 1.0ε₁ + 1.0ε₂ + 0.0ε₁ε₂

julia> 

julia> f3(x) = f1(x) ^ f2(x)
f3 (generic function with 1 method)

julia> 

julia> f3(t0)
100.0 + 790.7755278982138ε₁ + 790.7755278982138ε₂ + 6883.776373825795ε₁ε₂
```

Rob J Goedman
goedman@icloud.com

**Comment by briochemc** [comment]
Hi Rob,

> Hmm, that didn't work well (answered in mail and attached some files).

I'm sorry I fail to see how this did not work? It seems to me that the values are correct? Maybe I can't see one of the files sent via email?

Note that what I had in mind was a bit different. First, allow me to rewrite your example with slightly different notation:
```julia
julia> f(x) = x - x^3 + 4*x^2
f (generic function with 1 method)

julia> g(x) = x^2 - x
g (generic function with 1 method)

julia> h(x) = f(x)^g(x)
h (generic function with 1 method)
```
Then I use [sagemath](http://www.sagemath.org) (my Mathematica license is no more 😢) to derive formulae for the first and second derivatives of `h(x)`:
```sage
sage: f(x) = x - x^3 + 4*x^2
sage: g(x) = x^2 - x
sage: h(x) = f(x)^g(x)
sage: derivative(h(x), x, 1)
((2*x - 1)*log(-x^3 + 4*x^2 + x) + (3*x^2 - 8*x - 1)*(x^2 - x)/(x^3 - 4*x^2 - x))*(-x^3 + 4*x^2 + x)^(x^2 - x)
sage: derivative(h(x), x, 2)
((2*x - 1)*log(-x^3 + 4*x^2 + x) + (3*x^2 - 8*x - 1)*(x^2 - x)/(x^3 - 4*x^2 - x))^2*(-x^3 + 4*x^2 + x)^(x^2 - x) - (-x^3 + 4*x^2 + x)^(x^2 - x)*((3*x^2 - 8*x - 1)^2*(x^2 - x)/(x^3 - 4*x^2 - x)^2 - 2*(x^2 - x)*(3*x - 4)/(x^3 - 4*x^2 - x) - 2*(3*x^2 - 8*x - 1)*(2*x - 1)/(x^3 - 4*x^2 - x) - 2*log(-x^3 + 4*x^2 + x))
```
And I copy-paste those formulae to define Julia functions for the derivatives: 
```julia
julia> Dh(x) = ((2*x - 1)*log(-x^3 + 4*x^2 + x) + (3*x^2 - 8*x - 1)*(x^2 - x)/(x^3 - 4*x^2 - x))*(-x^3 + 4*x^2 + x)^(x^2 - x)
Dh (generic function with 1 method)

julia> D²h(x) = ((2*x - 1)*log(-x^3 + 4*x^2 + x) + (3*x^2 - 8*x - 1)*(x^2 - x)/(x^3 - 4*x^2 - x))^2*(-x^3 + 4*x^2 + x)^(x^2 - x) - (-x^3 + 4*x^2 + x)^(x^2 - x)*((3*x^2 - 8*x - 1)^2*(x^2 - x)/(x^3 - 4*x^2 - x)^2 - 2*(x^2 - x)*(3*x - 4)/(x^3 - 4*x^2 - x) - 2*(3*x^2 - 8*x - 1)*(2*x - 1)/(x^3 - 4*x^2 - x) - 2*log(-x^3 + 4*x^2 + x))
D²h (generic function with 1 method)
```
Now I want to compare the dual parts of `h` to `Dh` and `D²h`:
```julia
julia> using HyperDualNumbers

julia> x0 = 2.0
2.0

julia> t0 = hyper(x0, 1, 1, 0)
Hyper{Float64}(2.0, 1.0, 1.0, 0.0)

julia> abs(eps1(h(t0)) - Dh(x0)) < 5eps(Dh(x0))
true

julia> abs(eps1eps2(h(t0)) - D²h(x0)) < 5eps(D²h(x0))
true
```
And this is what we wanted to check! So to me that's all good, unless I'm missing something?

**Pull request merged**
